### ISSUE TITLE
Emoji Interferes With Texting

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1829]
Besides the longer outstanding issues of clicking on certain Links that just black out Caprine and require Relaunch to remedy, and Remove Button and such not working, a new issue has popped up.
When trying to type text there's a redundant Emoji sitting inside the text box at the right. It will not allow me to punctuate the sentence that finishes just there. I can't set the cursor near it. It then raises Emoji choices that  I don't want. 
Please get that Emoji Link out of my Texting Window. Having an Emoji Button next to it suffices.

---

Caprine 2.55.4
Electron 10.4.7
win32 6.1.7601
Locale: en-US

**Comment by lefterisgar** [comment]
Hey! As I had told you in an earlier post (#1814), those issues are not yet officially resolved. In the meantime, what you can do is download my fork from [here](https://github.com/lefterisgar/caprine/releases). Install it just as you would install an official release.

**Comment by PreachJohn** [comment]
' As I had told you in an earlier post ', the fork would not install. 
And the advice then was that i just had to wait until a new release.
But that said, I will try once more to install the fork.
Thanks much for the reply.

**Comment by lefterisgar** [comment]
No problem, if you need any help I can happily assist you. The problem is I don't know when the next release is going to be... It may happen tomorrow, it may happen next month.

**Comment by PreachJohn** [comment]
I downloaded the .exe. It appears to start to install, then quits.
Win7 Pro says it's a permissions issue.
So I check permissions. They are Allowed across the board. Only 'special
permissions' is inert to check for all 3 entities that can access my
system; Administrator, PreachJohn, System.
I looked at the registry key. Could see nothing to edit.
Neither Caprine 255.4 or the Fork have an entry in Program Files or Program
Files (x86). Which I find odd.
Reinstalled regular Caprine.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lefterisgar** [comment]
I truly don't know how to assist you, being a Linux user myself. There have been reports of my fork working on Windows 10 but that's it. You might be better off waiting for an official release.
On a side note, Windows 7 has reached its end-of-life so you should consider upgrading.

Again, sorry for making you go through all of this just to find it can't be installed. I was just trying to help.

**Comment by lefterisgar** [comment]
For anyone interested, I can confirm that it's actually NOT a Windows 7 issue. Look at the screenshot:
![εικόνα](https://user-images.githubusercontent.com/46350667/167262142-4399a8c6-3d86-4f32-9db6-b91fcf038a3f.png)

Windows 7 Ultimate 64-bit

**Comment by PreachJohn** [comment]
I am happy to tell you that having made sure that I have required
permissions, etc, etc no install of the Fork occurred no matter what I did,
but that I have finally found a way to install the Fork on Win7 Pro 64 bit.
In Downloads/R Click 2.55.4-4/Troubleshoot Compatibilities.
Do Not Click Recommended but the 2nd option 'based on problems you
noticed'. Then Click 'requires additional permissions'. 2.55.4-4 installed
right after. Yay!

**Comment by lefterisgar** [comment]
That's nice! Hope it was worth the trouble after all and all (or most of) your issues have been resolved!

**Comment by PreachJohn** [comment]
I did a System Restore/15 days back. Caprine 2.55.4-3 would no longer
install. I am an obsessive problem solver sometimes.
AVG Free was blocking. Ransomware/Allow is my ticket. Hope this tidbit
helps someone with Win7.
Thanks,
PreachJohn
PS---A lot of us think Win7 with layered defensive Apps is MS's best OS
ever. I will never move to Win10 or Plus.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by PreachJohn** [comment]
An Update on a simple work around when 255.4-3 won't load again on Startups
in Win7 Pro 64 bit.
I simply right click on its Icon pinned to the Start
Menu/Properties/Compatibility.
Even tho' it says it's on Win7 I still click on Win7 which activates
Apply/Ok.  It loads just fine after this work around.
I hope this is useful. This Iteration works just fine.
John Butkans

**Comment by mquevill** [comment]
This issue was fixed in v2.55.5. Upgrading to a newer official release should resolve this for you.

**Comment by PreachJohn** [comment]
Where is it fixed? I am on the suggested latest.
The blue Emoji is still there on the actual texting line exactly as before.
I ran into it again when I tried to place my cursor there to change
something. It then only pops up a bank of useless Emojis.
I have to bother with a workaround I have figured out. It is not fixed.
Sincerely,
John Butkans

**Comment by PreachJohn** [comment]
I wanted to punctuate Wed. with a period or just a ? mark. Place cursor
there and only Emoji choices pop up.
We have access to Emojis elsewhere already if we want them; React. This
blue Emoji choice doesn't belong on the messaging line. It interferes with
messaging.
That's what is not fixed as claimed.
Respectfully,
John Butkans
